from matplotlib.cbook import index_of

sample_str = (
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood. A woodchuck would chuck as much wood as "
    "a woodchuck would if a woodchuck could chuck wood."
) # sample text for checking: text generated by ChatGPT

# using split function to create a list of all words in the sample string
word_list = sample_str.split()

# taking count of each word and storing it in the list
count_of_each_word = {}
count = 0 # count of current word
# tuple for each word-count pair
length = []
for word in word_list:
    length.append(len(word))
    word = word.strip(" ") # removing space
    if word in count_of_each_word: # if the word is already there in the dictionary increment it's count
        count_of_each_word[word] += 1
    else:
        count_of_each_word[word] = 1 # if the word is not there in the dictionary add it and set the count to 1

print(count_of_each_word)
# printing the longest word and it's length
print(f"Length of longest word is ",max(length),f" and the word is {word_list[length.index(max(length))]}")
